### ISSUE TITLE
Path validation

### ISSUE THREAD

**Issue by feldrim** [feldrim/AnagramExperiment#1]
Thanks to Helmes Technical Lead, I could see the simple, litle yet critic fault. The program does not validate the path input.

**Comment by arwinneil** [comment]
Hello, browsing GitHub and found your issue, need help with that? 😄

**Comment by feldrim** [comment]
Solved with: https://github.com/feldrim/AnagramExperiment/commit/c179e07ce08f61ef473d65c868f0f5110029f4db
